Create the InputParser class
Cavonstavant/PLAZAAAAAAAAAAAAAAAAAAAAAAA pull request #12
Opened 2022-04-29 07:34 UTC by osvegn

This class will be used to parse the arguments of a command of pizza while the program is running

2022-04-29 12:01 UTC, osvegn commented
Wait while this https://github.com/Cavonstavant/PLAZAAAAAAAAAAAAAAAAAAAAAAA/pull/14 is open

2022-05-04 18:38 UTC, Cavonstavant approved these changes

2022-05-04 18:38 UTC, Cavonstavant commented on src/Parser/InputParser/InputParser.cpp
> +    ParserEX("Prossess the arguments for the InputParser class", Logger::INFO);
same

2022-05-04 18:38 UTC, Cavonstavant commented on src/Parser/InputParser/InputParser.cpp
> +        ParserEX("Invalide pizza name in the command", Logger::LOW);
Already better, Invalid w/o an e would be ideal
Consider adding the faulty pizza name to `what()`

2022-05-04 18:38 UTC, Cavonstavant commented on src/Parser/InputParser/InputParser.cpp
> +bool InputParser::_isValidePizzaName(const std::string &pizza) const
Valid not valide

2022-05-04 18:38 UTC, Cavonstavant commented on src/Parser/InputParser/InputParser.cpp
> +bool InputParser::_isValidePizzaSize(const std::string &pizzaSize) const
valid not valide

2022-05-04 18:38 UTC, Cavonstavant commented on src/Parser/InputParser/InputParser.cpp
> +        ParserEX("Invalide pizza size in the command", Logger::LOW);
Same as the pizza name

2022-05-04 18:38 UTC, Cavonstavant commented on src/Parser/InputParser/InputParser.cpp
> +        ParserEX("Invalide pizza number in the command", Logger::LOW);
same as the name and the size

2022-05-04 18:38 UTC, Cavonstavant commented on src/Parser/InputParser/InputParser.hpp
> +        void prossessArguments() override;
process not prossess

2022-05-04 18:38 UTC, Cavonstavant commented on src/Parser/InputParser/InputParser.hpp
> +/// \brief InputParser is a class use to parse command of pizza while the program is running
used to*

2022-05-04 18:40 UTC, Cavonstavant requested changes
need a bit of rework especially on exception throwing

2022-05-04 22:09 UTC, Cavonstavant approved these changes
LGTM!

2022-05-05 08:00 UTC, 31Nathan commented on src/Parser/InputParser/InputParser.hpp
> +        /// \return true if it's std::string is a valide pizza size, false otherwise.
It's "valid"

2022-05-05 08:00 UTC, 31Nathan commented on src/Parser/InputParser/InputParser.hpp
> +        /// \brief Check if the pizza number passed as parameter is valide.
Same

2022-05-05 08:00 UTC, 31Nathan commented on src/Parser/InputParser/InputParser.hpp
> +        /// \return true if it's std::string is a valide pizza number, false otherwise.
And we continue

2022-05-05 08:00 UTC, 31Nathan commented on src/Parser/InputParser/InputParser.hpp
> +        /// \brief Check if the pizza separator passed as parameter is valide.
Not going to do all

2022-05-05 08:00 UTC, 31Nathan commented on src/Parser/InputParser/InputParser.hpp
> +        /// \brief Store the command that will be prossess.
It's "process"

2022-05-05 08:00 UTC, 31Nathan commented on src/Parser/InputParser/InputParser.hpp
> +        /// \brief Store the separator that will use for prossessArgument.
Here we go again

2022-05-05 08:09 UTC, 31Nathan approved these changes

2022-05-05 08:12 UTC, merged