Core/70 kitchen status
Cavonstavant/PLAZAAAAAAAAAAAAAAAAAAAAAAA pull request #129
Opened 2022-05-20 23:08 UTC by osvegn

Fix some error with fridge vector.
Some things will be dirty, but it's normal because of a crazy vector.
Enqueue and Dequeue the fridge on "status" command to be display.

2022-05-20 23:48 UTC, Cavonstavant approved these changes
LGTM!

2022-05-20 23:54 UTC, Cavonstavant approved these changes

2022-05-21 14:24 UTC, 31Nathan requested changes

2022-05-21 14:24 UTC, 31Nathan commented on src/Core/Plazza.cpp
> +        // newKitchen.stop();
Remove, seem useless

2022-05-21 14:24 UTC, 31Nathan commented on src/Core/Kitchen/Kitchen.cpp
> +            obj->_fridge -= order;
if not  enough ingredients, no catch of the exception

2022-05-21 20:06 UTC, merged