Feature/15 ipc create wrapper class for unix message queue
Cavonstavant/PLAZAAAAAAAAAAAAAAAAAAAAAAA pull request #17
Opened 2022-05-01 16:18 UTC by Cavonstavant

Closes #15
Missing unit tests

2022-05-01 21:23 UTC, osvegn requested changes
Why exit(84) is called, but without throwing an error ?

2022-05-01 21:23 UTC, osvegn commented on src/MessageQueue/MessageQueue.cpp
> +        exit(84);
Throw an error before

2022-05-01 21:23 UTC, osvegn commented on src/MessageQueue/MessageQueue.cpp
> +        exit(84);
Same

2022-05-01 21:23 UTC, osvegn commented on src/MessageQueue/MessageQueue.cpp
> +        exit(84);
Same

2022-05-01 21:38 UTC, Cavonstavant commented
because

2022-05-03 14:20 UTC, osvegn requested changes
All is good, but need to do a valid test in message queue

2022-05-03 14:20 UTC, osvegn commented on tests/unit_tests/MessageQueue/MessageQueue_test.cpp
> +Test(MessageQueue, test_messageQueue_get_size)
Need a valide test

2022-05-03 15:31 UTC, osvegn approved these changes
LGTM

2022-05-03 15:32 UTC, merged