Create the cook class
Cavonstavant/PLAZAAAAAAAAAAAAAAAAAAAAAAA pull request #31
Opened 2022-05-05 08:13 UTC by osvegn

This part will create the cook class.

2022-05-16 14:14 UTC, osvegn commented
Need to handle the cooking time for each pizza.

2022-05-16 15:37 UTC, 31Nathan requested changes

2022-05-16 15:41 UTC, 31Nathan approved these changes
LGTM!

2022-05-18 08:06 UTC, Cavonstavant approved these changes
LGTM!

2022-05-18 08:27 UTC, merged