Adding Plazza Fridge
Cavonstavant/PLAZAAAAAAAAAAAAAAAAAAAAAAA pull request #76
Opened 2022-05-16 15:43 UTC by 31Nathan

Add Plazza Fridge to Kitchen Class
Fill it every refill time on the thread loop

2022-05-16 16:12 UTC, osvegn requested changes
Need minor change

2022-05-16 16:12 UTC, osvegn commented on src/Core/Kitchen/Kitchen.cpp
> +    for (size_t x = 0; x < IngredientNumber; ++x) {
use std::size_t

2022-05-16 17:48 UTC, Cavonstavant commented on src/Core/Kitchen/Kitchen.cpp
> +    for (size_t x = 0; x < IngredientNumber; ++x) {
Why @osvegn ?

2022-05-17 08:21 UTC, osvegn commented on src/Core/Kitchen/Kitchen.cpp
> +    for (size_t x = 0; x < IngredientNumber; ++x) {
size_t -> C
std::size_t -> C++
?

2022-05-18 07:41 UTC, merged