Add a blocking thread on the message queue
Cavonstavant/PLAZAAAAAAAAAAAAAAAAAAAAAAA pull request #93
Opened 2022-05-18 22:26 UTC by 31Nathan

Add a function for the blocking thread
Read the message queue and transform the command into a Pizza Object

2022-05-18 22:33 UTC, Cavonstavant requested changes
See you tomorrow

2022-05-19 07:48 UTC, Cavonstavant approved these changes

2022-05-19 07:52 UTC, osvegn requested changes
Need minor changes

2022-05-19 07:52 UTC, osvegn commented on src/Core/Kitchen/Kitchen.cpp
> +#include <iostream>
usefull ?

2022-05-19 07:52 UTC, osvegn commented on src/Core/Kitchen/Kitchen.hpp
>              static void _Cook(Kitchen *obj);
need more documentation

2022-05-19 07:52 UTC, osvegn commented on src/Core/Plazza.hpp
> +            std::map<pid_t, std::shared_ptr<MessageQueue>> _kitchenQueues;
need documentation

2022-05-19 09:31 UTC, osvegn approved these changes
LGTM

2022-05-19 09:38 UTC, merged